CREATE TABLE IF NOT EXISTS countries_languages (
    country_code VARCHAR(2) CHARACTER SET UTF8MB4,
    country_name VARCHAR(45) CHARACTER SET UTF8MB4,
    official_languages VARCHAR(20) CHARACTER SET UTF8MB4
);

INSERT INTO countries_languages VALUES
('AF','Afghanistan','Dari'),
('AF','Afghanistan','Pashto'),
('AL','Albania','Albanian'),
('DZ','Algeria','Arabic'),
('DZ','Algeria','Berber'),
('AS','American Samoa','English'),
('AS','American Samoa','Samoan'),
('AD','Andorra','Catalan'),
('AO','Angola','Portuguese'),
('AG','Antigua And Barbuda','English'),
('AR','Argentina','Spanish'),
('AM','Armenia','Armenian'),
('AW','Aruba','Dutch'),
('AW','Aruba','Papiamento'),
('AU','Australia','English'),
('AT','Austria','German'),
('AZ','Azerbaijan','Azerbaijani'),
('BS','Bahamas, The','English'),
('BH','Bahrain','Arabic'),
('BD','Bangladesh','Bengali'),
('BB','Barbados','English'),
('BY','Belarus','Belarusian'),
('BY','Belarus','Russian'),
('BE','Belgium','Dutch'),
('BE','Belgium','French'),
('BE','Belgium','German'),
('BZ','Belize','English'),
('BJ','Benin','French'),
('BM','Bermuda','English'),
('BT','Bhutan','Dzongkha'),
('BO','Bolivia','Spanish'),
('BA','Bosnia And Herzegovina','Bosnian'),
('BA','Bosnia And Herzegovina','Serbian'),
('BA','Bosnia And Herzegovina','Croatian'),
('BW','Botswana','English'),
('BW','Botswana','Setswana'),
('BR','Brazil','Portuguese'),
('BN','Brunei','Malay'),
('BG','Bulgaria','Bulgarian'),
('BF','Burkina Faso','French'),
('MM','Burma','Burmese'),
('BI','Burundi','Kirundi'),
('BI','Burundi','French'),
('BI','Burundi','English'),
('CV','Cabo Verde','Portuguese'),
('KH','Cambodia','Khmer'),
('CM','Cameroon','English'),
('CM','Cameroon','French'),
('CA','Canada','English'),
('CA','Canada','French'),
('KY','Cayman Islands','English'),
('CF','Central African Republic','French'),
('CF','Central African Republic','Sango'),
('TD','Chad','French'),
('TD','Chad','Arabic'),
('CL','Chile','Spanish'),
('CN','China','Standard Chinese'),
('CO','Colombia','Spanish'),
('KM','Comoros','Comorian'),
('KM','Comoros','Arabic'),
('KM','Comoros','French'),
('CG','Congo (Brazzaville)','French'),
('CD','Congo (Kinshasa)','French'),
('CK','Cook Islands','English'),
('CK','Cook Islands','Cook Islands Maori '),
('CR','Costa Rica','Spanish'),
('CI','Cote D’Ivoire','French'),
('HR','Croatia','Croatian'),
('CU','Cuba','Spanish'),
('CW','Curacao','Papiamento'),
('CW','Curacao','Dutch'),
('CW','Curacao','English'),
('CY','Cyprus','Greek'),
('CY','Cyprus','Turkish'),
('CZ','Czechia','Czech'),
('DK','Denmark','Danish'),
('DJ','Djibouti','French'),
('DJ','Djibouti','Arabic'),
('DM','Dominica','English'),
('DO','Dominican Republic','Spanish'),
('EC','Ecuador','Spanish'),
('EG','Egypt','Arabic'),
('SV','El Salvador','Spanish'),
('GQ','Equatorial Guinea','Spanish'),
('GQ','Equatorial Guinea','French'),
('GQ','Equatorial Guinea','Portuguese'),
('ER','Eritrea',NULL),
('EE','Estonia','Estonian'),
('ET','Ethiopia','Amharic'),
('FK','Falkland Islands (Islas Malvinas)','English'),
('FO','Faroe Islands','Faroese'),
('FO','Faroe Islands','Danish'),
('FJ','Fiji','iTaukei'),
('FJ','Fiji','English'),
('FJ','Fiji','Fiji Hindi'),
('FI','Finland','Finnish'),
('FI','Finland','Swedish'),
('FR','France','French'),
('GF','French Guiana','French'),
('PF','French Polynesia','French'),
('GA','Gabon','French'),
('GM','Gambia, The','English'),
('GE','Georgia','Georgian'),
('GE','Georgia','Abkhazian'),
('DE','Germany','German'),
('GH','Ghana','English'),
('GI','Gibraltar','English'),
('GR','Greece','Greek'),
('GL','Greenland','Greenlandic'),
('GD','Grenada','English'),
('GP','Guadeloupe','French'),
('GU','Guam','Chamorro'),
('GU','Guam','English'),
('GT','Guatemala','Spanish'),
('GN','Guinea','French'),
('GW','Guinea-Bissau','Portuguese'),
('GY','Guyana','English'),
('HT','Haiti','French'),
('HT','Haiti','Haitian Creole'),
('HN','Honduras','Spanish'),
('HK','Hong Kong','Chinese'),
('HK','Hong Kong','English'),
('HU','Hungary','Hungarian'),
('IS','Iceland','Icelandic'),
('IN','India','Hindi'),
('IN','India','English'),
('ID','Indonesia','Indonesian'),
('IR','Iran','Persian'),
('IQ','Iraq','Arabic'),
('IQ','Iraq','Kurdish'),
('IE','Ireland','English'),
('IE','Ireland','Irish'),
('IE','Ireland','Ulster Scots'),
('IM','Isle Of Man','English'),
('IL','Israel','Hebrew'),
('IT','Italy','Italian'),
('JM','Jamaica','English'),
('JP','Japan','Japanese'),
('JO','Jordan','Arabic'),
('KZ','Kazakhstan','Kazakh'),
('KE','Kenya','English'),
('KE','Kenya','Swahili'),
('KI','Kiribati','English'),
('KI','Kiribati','Gilbertese'),
('KP','Korea, North','Korean'),
('KR','Korea, South','Korean'),
('XK','Kosovo','Albanian'),
('XK','Kosovo','Serbian'),
('KW','Kuwait','Arabic'),
('KG','Kyrgyzstan','Kyrgyz'),
('LA','Laos','Lao'),
('LV','Latvia','Latvian'),
('LB','Lebanon','Arabic'),
('LS','Lesotho','Sesotho'),
('LS','Lesotho','English'),
('LR','Liberia','English'),
('LY','Libya','Arabic'),
('LI','Liechtenstein','German'),
('LT','Lithuania','Lithuanian'),
('LU','Luxembourg','Luxembourgish'),
('LU','Luxembourg','French'),
('LU','Luxembourg','German'),
('MO','Macau','Chinese'),
('MO','Macau','Portuguese'),
('MK','Macedonia','Macedonian'),
('MK','Macedonia','Albanian'),
('MG','Madagascar','Malagasy'),
('MG','Madagascar','French'),
('MW','Malawi','English'),
('MW','Malawi','Chichewa'),
('MY','Malaysia','Malay'),
('MV','Maldives','Dhivehi'),
('ML','Mali','French'),
('MT','Malta','Maltese'),
('MT','Malta','English'),
('MH','Marshall Islands','English'),
('MH','Marshall Islands','Marshallese'),
('MQ','Martinique','French'),
('MR','Mauritania','Arabic'),
('MU','Mauritius',NULL),
('YT','Mayotte','French'),
('MX','Mexico','Spanish'),
('FM','Micronesia, Federated States Of','English'),
('MD','Moldova','Romanian'),
('MC','Monaco','French'),
('MN','Mongolia','Mongolian'),
('ME','Montenegro','Montenegrin'),
('ME','Montenegro','Serbian'),
('ME','Montenegro','Bosnian'),
('ME','Montenegro','Croatian'),
('ME','Montenegro','Albanian'),
('MA','Morocco','Arabic'),
('MA','Morocco','Berber'),
('MZ','Mozambique','Portuguese'),
('NA','Namibia','English'),
('NP','Nepal','Nepali'),
('NL','Netherlands','Dutch'),
('NC','New Caledonia','French'),
('NZ','New Zealand','English'),
('NZ','New Zealand','Maori'),
('NI','Nicaragua','Spanish'),
('NE','Niger','French'),
('NG','Nigeria','English'),
('MP','Northern Mariana Islands','English'),
('MP','Northern Mariana Islands','Chamorro'),
('MP','Northern Mariana Islands','Carolinian'),
('NO','Norway','Norwegian'),
('OM','Oman','Arabic'),
('PK','Pakistan','English'),
('PK','Pakistan','Urdu'),
('PW','Palau','English'),
('PW','Palau','Palauan'),
('PW','Palau','Japanese'),
('PW','Palau','Sonsorolese'),
('PW','Palau','Tobian'),
('PA','Panama','Spanish'),
('PG','Papua New Guinea','English'),
('PG','Papua New Guinea','Hiri Motu'),
('PG','Papua New Guinea','Tok Pisin'),
('PY','Paraguay','Spanish'),
('PY','Paraguay','Guarani'),
('PE','Peru','Spanish'),
('PH','Philippines','English'),
('PH','Philippines','Filipino'),
('PL','Poland','Polish'),
('PT','Portugal','Portuguese'),
('PR','Puerto Rico','Spanish'),
('PR','Puerto Rico','English'),
('QA','Qatar','Arabic'),
('RE','Reunion','French'),
('RO','Romania','Romanian'),
('RU','Russia','Russian'),
('RW','Rwanda','English'),
('RW','Rwanda','French'),
('RW','Rwanda','Swahili'),
('RW','Rwanda','Kinyarwanda'),
('SH','Saint Helena, Ascension, And Tristan Da Cunha','English'),
('KN','Saint Kitts And Nevis','English'),
('LC','Saint Lucia','English'),
('VC','Saint Vincent And The Grenadines','English'),
('WS','Samoa','English'),
('WS','Samoa','Samoan'),
('SM','San Marino','Italian'),
('ST','Sao Tome And Principe','Portuguese'),
('SA','Saudi Arabia','Arabic'),
('SN','Senegal','French'),
('RS','Serbia','Serbian'),
('SC','Seychelles','Seychellois Creole'),
('SC','Seychelles','English'),
('SC','Seychelles','French');
INSERT INTO countries_languages VALUES
('SL','Sierra Leone','English'),
('SG','Singapore','English'),
('SG','Singapore','Malay'),
('SG','Singapore','Chinese'),
('SG','Singapore','Tamil'),
('SX','Sint Maarten','Dutch'),
('SX','Sint Maarten','English'),
('SK','Slovakia','Slovak'),
('SI','Slovenia','Slovne'),
('SB','Solomon Islands','English'),
('SO','Somalia','Somali'),
('SO','Somalia','Arabic'),
('ZA','South Africa','English'),
('ZA','South Africa','Afrikaans'),
('ZA','South Africa','Zulu'),
('ZA','South Africa','Xhosa'),
('ZA','South Africa','Northen Sotho'),
('ZA','South Africa','Tswana'),
('ZA','South Africa','Southern Sotho'),
('ZA','South Africa','Tsonga'),
('ZA','South Africa','Swazi'),
('ZA','South Africa','Venda'),
('ZA','South Africa','Southern Ndebele'),
('GS','South Georgia And South Sandwich Islands','English'),
('SS','South Sudan','English'),
('ES','Spain','Spanish'),
('LK','Sri Lanka','Sinhala'),
('LK','Sri Lanka','Tamil'),
('SD','Sudan','English'),
('SD','Sudan','Arabic'),
('SR','Suriname','Dutch'),
('SZ','Swaziland','Swazi'),
('SZ','Swaziland','English'),
('SE','Sweden','Swedish'),
('CH','Switzerland','German'),
('CH','Switzerland','French'),
('CH','Switzerland','Italian'),
('CH','Switzerland','Romansh'),
('SY','Syria','Arabic'),
('TW','Taiwan','Formosan languages'),
('TW','Taiwan','Hakka'),
('TW','Taiwan','Hokkien'),
('TW','Taiwan','Mandarin'),
('TW','Taiwan','Matsu'),
('TW','Taiwan','Taiwan Sign Language'),
('TJ','Tajikistan','Tajik'),
('TZ','Tanzania','Swahili'),
('TZ','Tanzania','English'),
('TZ','Tanzania','Arabic'),
('TH','Thailand','Thai'),
('TL','Timor-Leste','Tetum'),
('TL','Timor-Leste','Portuguese'),
('TG','Togo','French'),
('TO','Tonga','English'),
('TO','Tonga','Tongan'),
('TT','Trinidad And Tobago','English'),
('TN','Tunisia','Arabic'),
('TR','Turkey','Turkish'),
('TM','Turkmenistan','Turkmen'),
('TC','Turks And Caicos Islands','English'),
('TV','Tuvalu','English'),
('TV','Tuvalu','Tuvaluan'),
('UG','Uganda','English'),
('UG','Uganda','Swahili'),
('UA','Ukraine','Ukrainian'),
('AE','United Arab Emirates','Arabic'),
('GB','United Kingdom','English'),
('US','United States','English'),
('UY','Uruguay','Spanish'),
('UZ','Uzbekistan','Uzbek'),
('VU','Vanuatu','Bislama'),
('VU','Vanuatu','English'),
('VU','Vanuatu','French'),
('VE','Venezuela','Spanish'),
('VN','Vietnam','Vietnamese'),
('WF','Wallis And Futuna','French'),
('XW','West Bank','Palestinian Arabic'),
('XW','West Bank','Modern Hebrew'),
('YE','Yemen','Arabic'),
('ZM','Zambia','English'),
('ZW','Zimbabwe','Chewa'),
('ZW','Zimbabwe','Chibarwe'),
('ZW','Zimbabwe','English'),
('ZW','Zimbabwe','Kalanga'),
('ZW','Zimbabwe','Koisan'),
('ZW','Zimbabwe','Nambya'),
('ZW','Zimbabwe','Ndau'),
('ZW','Zimbabwe','Ndebele'),
('ZW','Zimbabwe','Shangani'),
('ZW','Zimbabwe','Shona'),
('ZW','Zimbabwe','Sotho'),
('ZW','Zimbabwe','Tonga'),
('ZW','Zimbabwe','Tswana'),
('ZW','Zimbabwe','Venda'),
('ZW','Zimbabwe','Xhosa');
